### ISSUE TITLE
*ngIf and other attribute colors (different theme)

### ISSUE THREAD

**Issue by vaindil** [ghaschel/vscode-angular-html#7]
This might not be a bug because I don't know how difficult it is to support additional themes. Feel free to close if you're not doing that, no problem; I just assume it's possible to update it for one theme and the highlight carries over to others. Everything looks correct in the suggested theme from the readme.

This theme is [One Dark Pro Monokai Darker Theme](https://marketplace.visualstudio.com/items?itemName=eserozvataf.one-dark-pro-monokai-darker).

* On the first line, `selectedCustomer` has two different colors inside the `*ngIf`.
* The text of the `title` attribute is different in the second-to-last line.

![image](https://user-images.githubusercontent.com/771134/48356903-4fd14400-e665-11e8-97c4-2acaf6efd45e.png)

**Comment by ghaschel** [comment]
About the first issue regarding ngIf, as the highlighting only applies scope names, it's up to the theme to apply that level of differentiation between objects and keys. For that part I'm using a built in pattern, so I don't really know how viable it is to recreate the wheel in that case.  But i will look further into that and let you know. That would be a nice plus.

And about the `title` in the second-to-last, i just pushed an update that covers that (i noticed that right away after publishing the fix for the other issue you reported)

Edit: Explaining a bit further: Actually, it's just like you told. The highlighting works by matching stuff it's considered syntax and applying scope names to that. And it's carried to another themes. But sometimes themes apply colors in a different way. E.g: The invalid scope applied to invalid attributes and invalid tags are not styled in a lot of themes, so it shows in plain boring white.

So recreating the wheel here would be remapping all JS / JSX expressions to apply to angular directives and grant it has only one color instead of two.

**Comment by ghaschel** [comment]
I checked it, and actually there isn't much I can do for it as a short term solution. It is actually up for the theme to style it the way you mentioned.

But i managed to differentiate a bit more from attributes and variables. I hope this helps, or even replace the need of a same color styling.

One Pro Monokai Darker
![color 2](https://user-images.githubusercontent.com/5878866/48514534-aac19180-e845-11e8-8f6b-c3dff8e41aef.png)
dark-plus-syntax
![color1](https://user-images.githubusercontent.com/5878866/48514535-aac19180-e845-11e8-89af-65d9c875cd46.png)

**Comment by vaindil** [comment]
Sorry for the delayed reply. Understandable that it's not something you can do, just figured I'd point it out in case it was an issue with the extension.

Doesn't look like the title text thing is fixed though. I'm on what VS Code says is the latest version, 0.0.29, and the issue is still there.

![image](https://user-images.githubusercontent.com/771134/48673571-9533bc80-eb10-11e8-9c80-7590eb37bb97.png)

**Comment by ghaschel** [comment]
I see... Naive of me, I completely forgot about special characters in generic attributes. I just pushed an update to cover that. It should be fixed now

Let me know if it is still happening

**Comment by vaindil** [comment]
Perfect, the title text looks good now. This extension is awesome, thank you so much for your quick fixes (and sorry my replies were delayed)!
